app = "cmdlwd-videobooth"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DATA_DIR = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = "shared-cpu-2x"
  memory = "4gb"

[[mounts]]
  source = "videobooth_data"
  destination = "/data"
  initial_size = "5gb"
